use std::process::Command;

#[test]
fn upgrade_help_lists_subcommand() {
    let output = Command::new(env!("CARGO_BIN_EXE_pinner"))
        .arg("upgrade")
        .arg("--help")
        .output()
        .unwrap();
    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("--script"));
    assert!(stdout.contains("--continue-on-ecosystem-error"));
}

#[test]
fn upgrade_walkthrough_with_agent_exits_2() {
    let output = Command::new(env!("CARGO_BIN_EXE_pinner"))
        .args(["--walkthrough", "--agent", "upgrade"])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(2));
}

#[test]
fn upgrade_script_mode_emits_shell_script() {
    let output = Command::new(env!("CARGO_BIN_EXE_pinner"))
        .args(["upgrade", "--script", "--ecosystem", "node"])
        .output()
        .unwrap();

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("#!/usr/bin/env bash"));
    assert!(stdout.contains("Generated by pinner upgrade --script"));
}
