use std::process::Command;
use tempfile::tempdir;

#[test]
fn upgrade_help_lists_subcommand() {
    let output = Command::new(env!("CARGO_BIN_EXE_pinner"))
        .arg("upgrade")
        .arg("--help")
        .output()
        .unwrap();
    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("--script"));
    assert!(stdout.contains("--continue-on-ecosystem-error"));
}

#[test]
fn upgrade_walkthrough_with_agent_exits_2() {
    let output = Command::new(env!("CARGO_BIN_EXE_pinner"))
        .args(["--walkthrough", "--agent", "upgrade"])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(2));
}

#[test]
fn upgrade_script_mode_emits_shell_script() {
    let output = Command::new(env!("CARGO_BIN_EXE_pinner"))
        .args(["upgrade", "--script", "--ecosystem", "node"])
        .output()
        .unwrap();

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("#!/usr/bin/env bash"));
    assert!(stdout.contains("Generated by pinner upgrade --script"));
}

#[test]
fn upgrade_script_mode_respects_gitignore() {
    let dir = tempdir().unwrap();
    std::fs::create_dir_all(dir.path().join(".worktrees")).unwrap();
    std::fs::write(dir.path().join(".gitignore"), ".worktrees/\n").unwrap();
    std::fs::write(dir.path().join(".mise.toml"), "[tools]\nnode = \"22\"\n").unwrap();
    std::fs::write(
        dir.path().join(".worktrees/.mise.toml"),
        "[tools]\nnode = \"20\"\n",
    )
    .unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_pinner"))
        .current_dir(dir.path())
        .args(["upgrade", "--script", "--ecosystem", "mise"])
        .output()
        .unwrap();

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("# manifest: .mise.toml"));
    assert!(!stdout.contains(".worktrees/.mise.toml"));
}
