[package]
name = "pinner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "pinner"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde_json = { workspace = true }
pinner-actions = { workspace = true }
pinner-azure = { workspace = true }
pinner-cargo = { workspace = true }
pinner-core = { workspace = true }
pinner-docker = { workspace = true }
pinner-ecosystem = { workspace = true }
pinner-gitlab = { workspace = true }
pinner-go = { workspace = true }
pinner-helm = { workspace = true }
pinner-k8s = { workspace = true }
pinner-terraform = { workspace = true }
pinner-mise = { workspace = true }
pinner-node = { workspace = true }
pinner-python = { workspace = true }
pinner-ruby = { workspace = true }
pinner-toolchain = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
jsonschema = { workspace = true }
predicates = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
